
############################################      Assignment-5    ####################################

                                  1. Use the previous deployment
                                  2. Deploy an NGINX deployment of 3 replicas
                                  3. Create an NGINX service of type ClusterIP
                                  4. Create an ingress service/ Apache to Apache service/ NGINX to NGINX service
                          

######################    Follow the below command to execute the Assignment      ############################################
Step-1    
      nano nginx-deployment.yml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest



        kubectl apply -f nginx-deployment.yaml


          

      
