##############################  1. Use the previous deployment    #############################
                                2. Create a service of type NodePort for NGINX deployment
                                3. Check the NodePort service on a browser to verify




apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


######################    Follow the below command to execute the Assignment      ############################################
     
     
   1-  nano nginx-service.yaml
   2-  paste the yml file 
   3-  
     
