apiVersion: v1
kind: Pod
metadata:
  name: first-pod-example
  labels:
    app: first-pod-example
spec:
  containers:
  - name: first-pod-example
    image: nginx
    ports:
    - name: nginx-port 
      containerPort: 80
