apiVersion: v1
kind: Service
metadata:
  name: service-pod-example-lb
spec:
  ports:
  - port: 80
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: first-pod-example
  type: LoadBalancer
  
  
  
  
