
############################################      Assignment-1    ####################################

                                1. Deploy a Kubernetes cluster for 3 nodes    
                                2. Create a NGINX deployment of 3 replicas
                            

######################    Follow the below command to execute the Assignment      ############################################
Step-1    
        Deploy a kubernetes cluster with Kubeadm Ec2 instanace with T2 medium
        Kubeadm cluster installation have seprate file attach. ( file name is kubeadm_installation  )

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
